; Dog.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Dog.java
.class public id/Dog
.super java/lang/Object
.implements id/Animal

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public getName()Ljava/lang/String;
  .limit stack 1
  .limit locals 1
  .line 5
  0: ldc "Dog"
  2: areturn
.end method

