; Id.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Id.java
.class public id/Id
.super java/lang/Object

.field public static global I

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static run()V
  .limit stack 2
  .limit locals 2
  .line 6
  0: new id/Dog
  3: dup
  4: invokespecial id/Dog/<init>()V
  7: astore_0
  .line 7
  8: aload_0
  9: invokeinterface id/Animal/getName()Ljava/lang/String; 1
  14: astore_1
  .line 8
  15: return
.end method

