; Array.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Array.java
.class public array/Array
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 4
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 4
  .limit locals 4
  .line 6
  0: bipush 10
  2: istore_1
  .line 7
  3: bipush 10
  5: newarray int
  7: astore_2
  .line 8
  8: iconst_3
  9: newarray int
  11: dup
  12: iconst_0
  13: iconst_1
  14: iastore
  15: dup
  16: iconst_1
  17: iconst_2
  18: iastore
  19: dup
  20: iconst_2
  21: iconst_3
  22: iastore
  23: astore_3
  .line 9
  24: return
.end method

