; Array.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Array.java
.class public array/Array
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 4
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public run()V
  .limit stack 4
  .limit locals 2
  .line 6
  0: iconst_3
  1: newarray int
  3: dup
  4: iconst_0
  5: iconst_1
  6: iastore
  7: dup
  8: iconst_1
  9: iconst_2
  10: iastore
  11: dup
  12: iconst_2
  13: iconst_3
  14: iastore
  15: astore_1
  .line 7
  16: aload_1
  17: iconst_1
  18: iconst_3
  19: iastore
  .line 8
  20: return
.end method

