; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public nested/MiniGoClass
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 2
  .limit locals 6
  .line 5
  0: aload_0
  1: astore_1
  .line 6
  2: bipush 100
  4: istore_2
  .line 8
  5: iload_2
  6: bipush 100
  8: iadd
  9: istore_3
  .line 9
  10: iload_2
  11: iload_3
  12: iadd
  13: istore 4
  .line 10
  15: iload 4
  17: istore 5
  .line 12
  19: bipush 100
  21: istore_3
  .line 13
  22: return
.end method

