; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public nested/MiniGoClass
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 2
  .limit locals 4
  .line 5
  0: bipush 100
  2: istore_1
  .line 7
  3: iload_1
  4: bipush 100
  6: iadd
  7: istore_2
  .line 8
  8: iload_1
  9: iload_2
  10: iadd
  11: istore_3
  .line 10
  12: bipush 100
  14: istore_2
  .line 11
  15: return
.end method

