; Final.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Final.java
.class public final_/Final
.super java/lang/Object

.field public name I

.method public <init>()V
  .limit stack 2
  .limit locals 1
  .line 7
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  .line 4
  4: aload_0
  5: bipush 18
  7: putfield final_/Final/name I
  .line 8
  10: aload_0
  11: bipush 100
  13: putfield final_/Final/name I
  .line 9
  16: return
.end method

