; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public struct/MiniGoClass
.super java/lang/Object

.field public name Ljava/lang/String;
.field public age I
.field public money F

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public doMethod()V
  .limit stack 0
  .limit locals 1
  .line 11
  0: return
.end method

