; Entity.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Entity.java
.interface public abstract program/Entity
; Flag ACC_SUPER not set, see JVM spec
.super java/lang/Object

.method public abstract getType()Ljava/lang/String;
.end method

