; GlobalClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source GlobalClass.java
.class public program/GlobalClass
.super java/lang/Object

.field public static a I
.field public static PI F

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static doSomething()V
  .limit stack 0
  .limit locals 0
  .line 8
  0: return
.end method

.method static <clinit>()V
  .limit stack 1
  .limit locals 0
  .line 4
  0: bipush 10
  2: putstatic program/GlobalClass/a I
  .line 5
  5: ldc 3.14
  7: putstatic program/GlobalClass/PI F
  10: return
.end method

