; Human.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Human.java
.class public program/Human
.super java/lang/Object
.implements program/Entity

.field public name Ljava/lang/String;
.field public age I

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public getType()Ljava/lang/String;
  .limit stack 1
  .limit locals 1
  .line 9
  0: ldc "Human"
  2: areturn
.end method

