; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public program/MiniGoClass
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main()V
  .limit stack 2
  .limit locals 4
  .line 6
  0: bipush 10
  2: istore_0
  .line 7
  3: ldc 20.1
  5: fstore_1
  .line 9
  6: getstatic program/GlobalClass/a I
  9: bipush 100
  11: iadd
  12: istore_0
  .line 10
  13: getstatic program/GlobalClass/PI F
  16: ldc 0.1
  18: fadd
  19: fstore_1
  .line 12
  20: invokestatic program/GlobalClass/doSomething()V
  .line 14
  23: new program/Human
  26: dup
  27: invokespecial program/Human/<init>()V
  30: astore_2
  .line 16
  31: aload_2
  32: invokevirtual program/Human/getType()Ljava/lang/String;
  35: pop
  .line 18
  36: aload_2
  37: astore_3
  .line 20
  38: aload_3
  39: invokeinterface program/Entity/getType()Ljava/lang/String; 1
  44: pop
  .line 21
  45: return
.end method

