; Human.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Human.java
.class public method/Human
.super java/lang/Object

.field public name Ljava/lang/String;

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public getName()Ljava/lang/String;
  .limit stack 1
  .limit locals 1
  .line 7
  0: aload_0
  1: getfield method/Human/name Ljava/lang/String;
  4: areturn
.end method

