; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public constructor/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 2
  .limit locals 3
  .line 4
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  .line 5
  4: bipush 10
  6: istore_1
  .line 6
  7: iload_1
  8: bipush 10
  10: iadd
  11: istore_2
  .line 7
  12: return
.end method

