; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public call/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static doSomething()V
  .limit stack 0
  .limit locals 0
  .line 5
  0: invokestatic call/Main/run()V
  .line 6
  3: return
.end method

.method public static run()V
  .limit stack 2
  .limit locals 3
  .line 9
  0: bipush 100
  2: istore_0
  .line 10
  3: bipush 100
  5: istore_1
  .line 11
  6: iload_0
  7: iload_1
  8: iadd
  9: istore_2
  .line 12
  10: return
.end method

