; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public call/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public run()V
  .limit stack 2
  .limit locals 2
  .line 5
  0: new call/Cat
  3: dup
  4: invokespecial call/Cat/<init>()V
  7: astore_1
  .line 6
  8: aload_1
  9: invokevirtual call/Cat/meow()V
  .line 7
  12: return
.end method

