; Return.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Return.java
.class public return_/Return
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static getInt()I
  .limit stack 1
  .limit locals 0
  .line 5
  0: iconst_1
  1: ireturn
.end method

.method public static getBool()Z
  .limit stack 1
  .limit locals 0
  .line 9
  0: iconst_1
  1: ireturn
.end method

.method public static getString()Ljava/lang/String;
  .limit stack 1
  .limit locals 0
  .line 13
  0: ldc ""
  2: areturn
.end method

.method public static getFloat()F
  .limit stack 1
  .limit locals 0
  .line 17
  0: fconst_1
  1: freturn
.end method

.method public static getDog()Lreturn_/Animal;
  .limit stack 2
  .limit locals 0
  .line 21
  0: new return_/Dog
  3: dup
  4: invokespecial return_/Dog/<init>()V
  7: areturn
.end method

