; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public str/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static run()V
  .limit stack 2
  .limit locals 2
  .line 5
  0: new java/lang/StringBuilder
  3: dup
  4: invokespecial java/lang/StringBuilder/<init>()V
  7: astore_0
  .line 6
  8: aload_0
  9: ldc "a"
  11: invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
  14: pop
  .line 7
  15: aload_0
  16: ldc "b"
  18: invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
  21: pop
  .line 8
  22: aload_0
  23: invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
  26: astore_1
  .line 9
  27: return
.end method

.method public static A()Ljava/lang/String;
  .limit stack 1
  .limit locals 0
  .line 12
  0: ldc "a"
  2: areturn
.end method

