; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public reop/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public run()V
  .limit stack 2
  .limit locals 4
  .line 5
  0: ldc "a"
  2: astore_1
  .line 6
  3: ldc "b"
  5: astore_2
  .line 7
  6: aload_1
  7: aload_2
  8: invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
  11: istore_3
  .line 8
  12: return
.end method

