; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public float_/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 4
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public run()V
  .limit stack 2
  .limit locals 4
  .line 6
  0: ldc 5.6
  2: fstore_1
  .line 7
  3: ldc 4.2
  5: fstore_2
  .line 8
  6: fload_1
  7: fload_2
  8: fcmpg
  9: ifge Label16
  12: iconst_1
  13: goto Label17
Label16:
  16: iconst_0
Label17:
  17: istore_3
  .line 9
  18: return
  ; append_frame (frameNumber = 0)
  ; frame_type = 253, offset_delta = 16
  ; frame bytes: 253 0 16 2 2 
  .stack 
    offset 16
    locals Float
    locals Float
    .end stack
  ; same_locals_1_stack_item_frame (frameNumber = 1)
  ; frame_type = 64, offset_delta = 0
  ; frame bytes: 64 1 
  .stack 
    offset 17
    locals Float
    locals Float
    stack Integer
    .end stack
.end method

