; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public i2f/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static run()V
  .limit stack 1
  .limit locals 2
  .line 5
  0: bipush 100
  2: istore_0
  .line 6
  3: iload_0
  4: i2f
  5: fstore_1
  .line 7
  6: return
.end method

