; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public clinit/Main
.super java/lang/Object

.field public static global I

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method static <clinit>()V
  .limit stack 1
  .limit locals 0
  .line 4
  0: ldc -140000
  2: putstatic clinit/Main/global I
  5: return
.end method

