; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public global/MiniGoClass
.super java/lang/Object

.field static e I

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 0
  .limit locals 1
  .line 10
  0: return
.end method

.method static <clinit>()V
  .limit stack 1
  .limit locals 0
  .line 5
  0: bipush 100
  2: putstatic global/MiniGoClass/e I
  5: return
.end method

