; Static.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Static.java
.class public static_/Static
.super java/lang/Object

.field public static G1 I
.field public static G2 I
.field public static G3 I

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method static <clinit>()V
  .limit stack 2
  .limit locals 0
  .line 4
  0: bipush 100
  2: putstatic static_/Static/G1 I
  .line 5
  5: getstatic static_/Static/G1 I
  8: bipush 100
  10: iadd
  11: putstatic static_/Static/G2 I
  .line 6
  14: getstatic static_/Static/G1 I
  17: getstatic static_/Static/G2 I
  20: iadd
  21: putstatic static_/Static/G3 I
  24: return
.end method

