; Call.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Call.java
.class public callst/Call
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static getInt()I
  .limit stack 1
  .limit locals 0
  .line 5
  0: bipush 100
  2: ireturn
.end method

.method public static run()V
  .limit stack 1
  .limit locals 0
  .line 10
  0: invokestatic callst/Call/getInt()I
  3: pop
  .line 11
  4: return
.end method

