; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public ifstmt/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static doSomething()V
  .limit stack 1
  .limit locals 2
  .line 5
  0: iconst_1
  1: istore_0
  .line 6
  2: iload_0
  3: ifeq Label12
  .line 7
  6: bipush 10
  8: istore_1
  .line 8
  9: goto Label15
Label12:
  .line 9
  12: bipush 10
  14: istore_1
Label15:
  .line 11
  15: return
  ; append_frame (frameNumber = 0)
  ; frame_type = 252, offset_delta = 12
  ; frame bytes: 252 0 12 1 
  .stack 
    offset 12
    locals Integer
    .end stack
  ; same_frame (frameNumber = 1)
  ; frame_type = 2, offset_delta = 2
  ; frame bytes: 2 
  .stack 
    offset 15
    locals Integer
    .end stack
.end method

