; IntLiteral.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source IntLiteral.java
.class public expr/IntLiteral
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public run()V
  .limit stack 1
  .limit locals 2
  .line 5
  0: ldc 10000000
  2: istore_1
  .line 6
  3: return
.end method

