; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public not/Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static run()V
  .limit stack 1
  .limit locals 2
  .line 5
  0: iconst_0
  1: istore_0
  .line 6
  2: iload_0
  3: ifne Label10
  6: iconst_1
  7: goto Label11
Label10:
  10: iconst_0
Label11:
  11: istore_1
  .line 7
  12: return
  ; append_frame (frameNumber = 0)
  ; frame_type = 252, offset_delta = 10
  ; frame bytes: 252 0 10 1 
  .stack 
    offset 10
    locals Integer
    .end stack
  ; same_locals_1_stack_item_frame (frameNumber = 1)
  ; frame_type = 64, offset_delta = 0
  ; frame bytes: 64 1 
  .stack 
    offset 11
    locals Integer
    stack Integer
    .end stack
.end method

