; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public variable/MiniGoClass
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static doSomething()V
  .limit stack 1
  .limit locals 2
  .line 6
  0: bipush 10
  2: istore_0
  .line 9
  3: return
.end method

