; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public variable/MiniGoClass
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static doSomething()V
  .limit stack 2
  .limit locals 5
  .line 5
  0: iconst_1
  1: istore_0
  .line 6
  2: fconst_2
  3: fstore_1
  .line 7
  4: iconst_1
  5: istore_2
  .line 8
  6: ldc ""
  8: astore_3
  .line 9
  9: new variable/Dog
  12: dup
  13: invokespecial variable/Dog/<init>()V
  16: astore 4
  .line 10
  18: return
.end method

