; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.class public variable/MiniGoClass
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static doSomething()V
  .limit stack 2
  .limit locals 2
  .line 5
  0: new variable/Dog
  3: dup
  4: invokespecial variable/Dog/<init>()V
  7: astore_0
  .line 6
  8: aload_0
  9: getfield variable/Dog/name Ljava/lang/String;
  12: astore_1
  .line 7
  13: return
.end method

