; Animal.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Animal.java
.interface public abstract interface_/Animal
; Flag ACC_SUPER not set, see JVM spec
.super java/lang/Object

.method public abstract getString()Ljava/lang/String;
.end method

.method public abstract getInt()I
.end method

.method public abstract getArr3()[[[I
.end method

.method public abstract putArr2([[I)F
.end method

.method public abstract getBool()Z
.end method

