; Dog.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Dog.java
.class public interface_/Dog
.super java/lang/Object

.field public name Ljava/lang/String;
.field public age I

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public attack(Linterface_/Animal;)V
  .limit stack 2
  .limit locals 2
  .line 9
  0: aload_1
  1: invokeinterface interface_/Animal/getBool()Z 1
  6: pop
  .line 10
  7: aload_0
  8: aload_1
  9: invokevirtual interface_/Dog/attack(Linterface_/Animal;)V
  .line 11
  12: return
.end method

