; MiniGoClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source MiniGoClass.java
.interface public abstract interface_/MiniGoClass
; Flag ACC_SUPER not set, see JVM spec
.super java/lang/Object

.method public abstract prototype1()V
.end method

.method public abstract prototype2()V
.end method

.method public abstract prototype3()V
.end method

