; Main.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 65.0
.source Main.java
.class public Main
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 1
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 2
  .limit locals 1
  .line 3
  0: getstatic java/lang/System/out Ljava/io/PrintStream;
  3: ldc "Hello world!"
  5: invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
  .line 4
  8: return
.end method

.method public static foo()V
  .limit stack 2
  .limit locals 3
  .line 8
  0: iconst_1
  1: istore_0
  .line 9
  2: iconst_2
  3: istore_1
  .line 10
  4: iload_0
  5: iload_1
  6: iadd
  7: istore_2
  .line 11
  8: return
.end method

